"""Changed fileLog timestamp column data type from string to datetime

Revision ID: 9d2b657be7d6
Revises: 8507af6e731e
Create Date: 2026-01-01 21:41:03.471933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d2b657be7d6'
down_revision = '8507af6e731e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.DateTime(),
               nullable=True)
    
    conn = op.get_bind()
    conn.execute(sa.text("DELETE FROM file_logs"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
