"""Add login capability to Staff table

Revision ID: ee762920d8cd
Revises: acbfe959f4bc
Create Date: 2026-01-01 10:10:49.419239

"""
from alembic import op
import sqlalchemy as sa
from werkzeug.security import generate_password_hash


# revision identifiers, used by Alembic.
revision = 'ee762920d8cd'
down_revision = 'acbfe959f4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))    #temporarily set nullable to true
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True)) #temporarily set nullable to true


    #Backfill existing rows
    connection = op.get_bind()
    staff_rows = connection.execute(sa.text("SELECT staff_id, name FROM staff")).fetchall()

    for row in staff_rows:
        username = f"{row.staff_id}_{row.name[:3]}_2025"
        default_password = f"{row.staff_id}_123"

        password_hash = generate_password_hash(default_password)
        connection.execute(sa.text("UPDATE staff SET username=:u, password_hash =:p WHERE staff_id =:id"),{"u": username, "p":password_hash, "id": row.staff_id})

    with op.batch_alter_table('staff') as batch_op:
        batch_op.alter_column('username', nullable = False)
        batch_op.alter_column('password_hash', nullable = False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('password_hash')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
